### ISSUE TITLE
Extract skills and specialisations from the core rulebook 2022

### ISSUE THREAD

**Issue by huin** [huin/travdata#18]
Proposed extracted data structures as two types of table:

1. A table containing all top-level skills, with columns:
   * skill name,
   * skill description.
2. One table per top-level skill that has specialities, with columns:
   * speciality name,
   * description and examples of a skill check combined.

**Comment by wileyma2000** [comment]
https://forum.mongoosepublishing.com/threads/travdata-getting-data-out-of-the-pdfs.124617/

Mongoose recently posted this repo to extract data from the PDFs.  From a quick glance it looks like it works for just the Core 2022 rule book, but I could be wrong.  Hope you don’t mind me posting something here.  

Cheers

**Comment by huin** [comment]
Fixed in 396e99d1520a88c2d004af3c6f938eaad7a61414.
